### ISSUE TITLE
a typo

### ISSUE THREAD

**Issue by makc** [Iranon/GDSL-Sketchy_Shader#1]
It is strength, not [strenght](https://github.com/Iranon/GDSL-Sketchy_Shader/blob/master/shader/Sketchy_Shader-GDSL.shader#L12)

**Comment by Iranon** [comment]
Now it is correct. Thank you!

**Comment by makc** [comment]
No it is not [lol](https://github.com/Iranon/GDSL-Sketchy_Shader/blob/master/material/Sketchy_Shader-GDSL_Mat.tres#L9)

**Comment by Iranon** [comment]
The shader has been corrected. The .tres file is generated inside Godot. If you download it you will notice that it will update automatically when you save the project. Pretty superfluous, but I will upload the updated .tres file too.
